version: 0.2
env:
  variables:
    SDK_URL: "https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip"
    ANDROID_HOME: "/DevTools/Android" 
    ANDROID_VERSION: 28
    ANDROID_BUILD_TOOLS_VERSION: 27.0.3
phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      # Download Android SDK
      - mkdir -p "$ANDROID_HOME/cmdline-tools/"
      - curl -o $ANDROID_HOME/cmdline-tools/sdk.zip $SDK_URL 
      - unzip $ANDROID_HOME/cmdline-tools/sdk.zip -d ANDROID_HOME/cmdline-tools
      - rm $ANDROID_HOME/cmdline-tools/sdk.zip
      - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools
      - export PATH="$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
      # Install Android Build Tool and Libraries
      - yes | sdkmanager --licenses 
      - sdkmanager --update
      - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platforms;android-${ANDROID_VERSION}" 
      # Install Build Essentials
      - apt-get update && apt-get install build-essential -y && apt-get install file -y && apt-get install apt-utils -y
      # used for app signing
      - apt-get install zipalign -y && apt-get install apksigner -y
  build:
    commands:
      - echo Build started on `date`
      - gradle --stacktrace build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/build/outputs/apk/**/*
  discard-paths: no